version: 2.1

jobs:
  build_integration_target:
    resource_class: xlarge
    docker:
      - image: cimg/rust:1.53.0-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-build-{{ .Revision }}-v1
      - run:
          name: Get substrate
          command: ./scripts/get_substrate.sh --fast
      - run:
          name: Build release
          command: |
            WASM_BUILD_RUSTFLAGS='--cfg feature="integration"' cargo +nightly-2021-06-01 build --release --features integration
      - save_cache:
          key: cargo-build-{{ .Revision }}-v1
          paths:
            - ./target
            - ~/.cargo
      - save_cache:
          key: gateway-{{ .Revision }}
          paths:
            - ./target/release/gateway

  integration_test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - gateway-{{ .Revision }}
      - run:
          name: check for gateway binary
          command: |
            ls -la
            find ./target
            [ -f ./target/release/gateway ] || ( echo "Missing gateway build" && exit 1 )
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: yarn install
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.yarn
            - ./node_modules
      - run:
          name: Run Tests
          command: yarn test __tests__/extract_scen.js

workflows:
  integration_test:
    jobs:
      - build_integration_target:
          name: "Build Integration Target"

      - integration_test:
          name: "Integration Test"
          requires:
            - "Build Integration Target"
